export default {
    APPLICATION_HIDE: 'APPLICATION_HIDE',
    APPLICATION_SHOW: 'APPLICATION_SHOW',

    APPLICATION_SET_STATUSBAR_COLOR: 'APPLICATION_SET_STATUSBAR_COLOR',

    APPLICATION_OVERLAY_MENU_SET: 'APPLICATION_OVERLAY_MENU_SET',
    APPLICATION_OVERLAY_MENU_CLOSE: 'APPLICATION_OVERLAY_MENU_CLOSE'
};
