export default {
    COMMENTS_LIST_REQUEST: 'COMMENTS_LIST_REQUEST',
    COMMENTS_LIST_SUCCESS: 'COMMENTS_LIST_SUCCESS',
    COMMENTS_LIST_FAIL: 'COMMENTS_LIST_FAIL',

    COMMENTS_LIST_REFRESH_REQUEST: 'COMMENTS_LIST_REFRESH_REQUEST',
    COMMENTS_LIST_REFRESH_SUCCESS: 'COMMENTS_LIST_REFRESH_SUCCESS',
    COMMENTS_LIST_REFRESH_FAIL: 'COMMENTS_LIST_REFRESH_FAIL',

    COMMENTS_REMOVE_REQUEST: 'COMMENTS_REMOVE_REQUEST',

    COMMENTS_ADD_REQUEST: 'COMMENTS_ADD_REQUEST',
    COMMENTS_ADD_SUCCESS: 'COMMENTS_ADD_SUCCESS',
    COMMENTS_ADD_FAIL: 'COMMENTS_ADD_FAIL'
};
