export default {
    FEED_LIST_REQUEST: 'FEED_LIST_REQUEST',
    FEED_LIST_SUCCESS: 'FEED_LIST_SUCCESS',
    FEED_LIST_FAIL: 'FEED_LIST_FAIL',

    FEED_LIST_REFRESH_REQUEST: 'FEED_LIST_REFRESH_REQUEST',
    FEED_LIST_REFRESH_SUCCESS: 'FEED_LIST_REFRESH_SUCCESS',
    FEED_LIST_REFRESH_FAIL: 'FEED_LIST_REFRESH_FAIL',

    FEED_LIST_LOCAL: 'FEED_LIST_LOCAL',

    FEED_FLUSH: 'FEED_FLUSH'
};
