export default {
    POEM_UPDATE: 'POEM_UPDATE',

    POEM_REMOVE_REQUEST: 'POEM_REMOVE_REQUEST',
    POEM_REMOVE_SUCCESS: 'POEM_REMOVE_SUCCESS',
    POEM_REMOVE_FAIL: 'POEM_REMOVE_FAIL',

    POEM_LOAD_ITEM: 'POEM_LOAD_ITEM'
};
