export default {
    USER_SIGN_IN_REQUEST: 'USER_SIGN_IN_REQUEST',
    USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
    USER_SIGN_IN_FAIL: 'USER_SIGN_IN_FAIL',

    USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
    USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL: 'USER_DETAILS_FAIL'
};
